require("fidget").setup()
require("nvim-autopairs").setup()
require("colorizer").setup()
require("refactoring").setup()
require("gomove").setup()
require("which-key").setup()
require("neoclip").setup()
