#!/bin/bash

pushd "$NVIM_CONFIG" > /dev/null
find . -type f -print0 | xargs -0 dos2unix
popd > /dev/null

pushd "$NVIM_PLUGIN_PATH" > /dev/null
find . -type f -print0 | xargs -0 dos2unix
popd > /dev/null
